defmodule CartographBackend.Dsl.ExpanderTest do
  # DB-backed: the expander resolves job references through TaskDefinition rows.
  use CartographBackend.DataCase, async: true

  alias CartographBackend.Dsl.{Expander, Flow, IfNode, Parser, StepSpec}
  alias CartographBackend.Groups.{Group, Project}
  alias CartographBackend.Tasks.TaskDefinition
  alias CartographBackend.Accounts.{User, Membership}

  @generic_error "Job reference not found or access denied"

  # ── Helpers ───────────────────────────────────────────────────────────────────

  defp insert_group(name) do
    %Group{} |> Group.changeset(%{name: name}) |> Repo.insert!()
  end

  defp insert_project(name, group_id) do
    %Project{} |> Project.changeset(%{name: name, group_id: group_id}) |> Repo.insert!()
  end

  # `identifier` defaults to a slug of the name; the public `code`
  # (`<identifier>-<suffix>`) is generated by the changeset.
  defp insert_task(name, dsl, attrs \\ %{}) do
    identifier = attrs[:identifier] || slug(name)

    %TaskDefinition{}
    |> TaskDefinition.changeset(
      Map.merge(%{name: name, identifier: identifier, dsl: dsl}, attrs)
    )
    |> Repo.insert!()
  end

  defp slug(name), do: name |> String.downcase() |> String.replace(~r/[^a-z0-9]+/, "-")

  defp insert_user(name, attrs \\ %{}) do
    %User{}
    |> User.changeset(
      Map.merge(%{name: name, email: "#{name}@ex.com", password: "secret123"}, attrs)
    )
    |> Repo.insert!()
  end

  defp grant(user, type, id, level) do
    %Membership{}
    |> Membership.changeset(%{
      user_id: user.id,
      subject_type: type,
      subject_id: id,
      access_level: level
    })
    |> Repo.insert!()
  end

  defp parse!(dsl) do
    {:ok, parsed} = Parser.parse(dsl)
    parsed.steps
  end

  # ── Happy path ────────────────────────────────────────────────────────────────

  test "`use \"<code>\"` resolves and inlines the referenced job's steps (authorized)" do
    g = insert_group("infra")
    p = insert_project("linux", g.id)
    target = insert_task("backup", ~s|backup { step "middle" }|, %{project_id: p.id})

    user = insert_user("alice")
    grant(user, "group", g.id, 10)

    steps = parse!(~s|caller { step "a" use "#{target.code}" step "b" }|)

    assert {:ok, expanded} = Expander.expand(steps, %{user: user})

    assert [
             %StepSpec{name: "a"},
             %StepSpec{name: "middle"},
             %StepSpec{name: "b"}
           ] = expanded
  end

  test "`job \"<code>\"` is an alias of `use` and resolves identically" do
    g = insert_group("g")
    p = insert_project("p", g.id)
    target = insert_task("helper", ~s|helper { step "fromHelper" }|, %{project_id: p.id})

    user = insert_user("carol")
    grant(user, "project", p.id, 10)

    steps = parse!(~s|caller { job "#{target.code}" }|)

    assert {:ok, [%StepSpec{name: "fromHelper"}]} = Expander.expand(steps, %{user: user})
  end

  test "resolution is global: references a job in another project the user can see" do
    g = insert_group("g")
    p1 = insert_project("p1", g.id)
    p2 = insert_project("p2", g.id)
    target = insert_task("shared", ~s|shared { step "fromP2" }|, %{project_id: p2.id})

    user = insert_user("dave")
    grant(user, "group", g.id, 10)

    steps = parse!(~s|caller { use "#{target.code}" }|)

    assert {:ok, [%StepSpec{name: "fromP2"}]} = Expander.expand(steps, %{user: user})
  end

  # ── SECURITY: no access + no oracle ───────────────────────────────────────────

  test "cross-tenant bypass BLOCKED: user without :view on the referenced job → generic error" do
    g = insert_group("secret-group")
    p = insert_project("secret-proj", g.id)
    secret = insert_task("secret-job", ~s|secret { step "stolen" }|, %{project_id: p.id})

    # user has NO membership anywhere
    user = insert_user("attacker")

    steps = parse!(~s|caller { use "#{secret.code}" }|)

    assert {:error, @generic_error} = Expander.expand(steps, %{user: user})
  end

  test "no enumeration oracle: nonexistent and forbidden return the IDENTICAL message" do
    g = insert_group("g")
    p = insert_project("p", g.id)
    forbidden_task = insert_task("forbidden", ~s|t { step "x" }|, %{project_id: p.id})

    user = insert_user("nobody")

    forbidden_ref = parse!(~s|c { use "#{forbidden_task.code}" }|)
    nonexistent_ref = parse!(~s|c { use "ghost-00000000" }|)

    assert {:error, forbidden_msg} = Expander.expand(forbidden_ref, %{user: user})
    assert {:error, notfound_msg} = Expander.expand(nonexistent_ref, %{user: user})

    assert forbidden_msg == notfound_msg
    assert forbidden_msg == @generic_error
  end

  # ── Cycle detection ───────────────────────────────────────────────────────────

  test "cycle via self-reference is detected" do
    g = insert_group("g")
    p = insert_project("p", g.id)

    # Create the task, then update its DSL to reference itself by code.
    loop = insert_task("loop", ~s|loop { step "noop" }|, %{project_id: p.id})

    loop =
      loop
      |> TaskDefinition.update_changeset(%{dsl: ~s|loop { use "#{loop.code}" }|})
      |> Repo.update!()

    user = insert_user("frank")
    grant(user, "group", g.id, 10)

    assert {:error, "Circular job reference detected: " <> _} =
             Expander.expand(parse!(loop.dsl), %{user: user})
  end

  test "mutual cycle (A → B → A) is detected" do
    g = insert_group("g")
    p = insert_project("p", g.id)

    a = insert_task("jobA", ~s|jobA { step "noop" }|, %{project_id: p.id})
    b = insert_task("jobB", ~s|jobB { step "noop" }|, %{project_id: p.id})

    a =
      a
      |> TaskDefinition.update_changeset(%{dsl: ~s|jobA { use "#{b.code}" }|})
      |> Repo.update!()

    _b =
      b
      |> TaskDefinition.update_changeset(%{dsl: ~s|jobB { use "#{a.code}" }|})
      |> Repo.update!()

    user = insert_user("gina")
    grant(user, "group", g.id, 10)

    assert {:error, "Circular job reference detected: " <> _} =
             Expander.expand(parse!(a.dsl), %{user: user})
  end

  # ── System (cron) context bypasses authorization ──────────────────────────────

  test ":system context resolves a ref without an authorized user" do
    g = insert_group("g")
    p = insert_project("p", g.id)
    target = insert_task("cronTarget", ~s|t { step "cronStep" }|, %{project_id: p.id})

    steps = parse!(~s|caller { use "#{target.code}" }|)

    assert {:ok, [%StepSpec{name: "cronStep"}]} = Expander.expand(steps, :system)
  end

  # ── Passthrough ───────────────────────────────────────────────────────────────

  test "non-job steps pass through untouched" do
    steps = parse!(~s|t { step "one" step "two" }|)
    assert {:ok, [%StepSpec{name: "one"}, %StepSpec{name: "two"}]} = Expander.expand(steps, :system)
  end

  # ── Flow-id provenance (CONTRACT with Dsl.Flow) ───────────────────────────────
  # The execution overlay correlates step_execution.flow_node_id with the graph
  # built by Dsl.Flow, so both modules MUST derive the same structural ids from
  # the same DSL. If either id scheme changes, this suite must fail.

  # In-order flow_ids of an expanded AST (both if branches, then before else).
  defp expanded_ids(nodes) do
    Enum.flat_map(nodes, fn
      %StepSpec{flow_id: id} -> [id]
      %IfNode{then_steps: t, else_steps: e} -> expanded_ids(t) ++ expanded_ids(e)
    end)
  end

  # In-order ids of the step nodes of a Flow tree (descends branches, sub-jobs).
  defp flow_step_ids(nodes) do
    Enum.flat_map(nodes, fn
      %{"kind" => "step", "id" => id} -> [id]
      %{"kind" => "if", "then" => t, "else" => e} -> flow_step_ids(t) ++ flow_step_ids(e)
      %{"kind" => "job", "steps" => steps} -> flow_step_ids(steps)
      _ -> []
    end)
  end

  test "CONTRACT: expander flow_ids == Flow step-node ids (steps, branches, nested sub-jobs)" do
    g = insert_group("g")
    p = insert_project("p", g.id)

    inner = insert_task("inner", ~s|inner { step "deep" }|, %{project_id: p.id})

    sub =
      insert_task(
        "sub",
        ~s|sub { step "s1" if state["k"] { step "s2" } else { step "s3" } use "#{inner.code}" }|,
        %{project_id: p.id}
      )

    dsl =
      ~s|main { step "a" if state["x"] { step "b" use "#{sub.code}" } else { step "c" } use "#{sub.code}" step "z" }|

    assert {:ok, flow} = Flow.build(dsl, :system)
    assert {:ok, expanded} = Expander.expand(parse!(dsl), :system)

    ids = expanded_ids(expanded)
    assert ids == flow_step_ids(flow)
    refute nil in ids

    # Spot-checks so the id shape stays legible in the test itself:
    assert "0" in ids          # step "a"
    assert "1/t0" in ids       # step "b" (then-branch)
    assert "1/t1/j0" in ids    # sub's "s1" via then-branch use
    assert "1/e0" in ids       # step "c" (else-branch)
    assert "2/j1/t0" in ids    # sub's "s2" via top-level use
    assert "2/j2/j0" in ids    # inner's "deep": use inside use
    assert "3" in ids          # step "z"
  end

  test "flow_ids of plain top-level steps are the positional indexes" do
    steps = parse!(~s|t { step "one" step "two" }|)

    assert {:ok, [%StepSpec{flow_id: "0"}, %StepSpec{flow_id: "1"}]} =
             Expander.expand(steps, :system)
  end
end
