defmodule CartographBackendWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :cartograph_backend
  use Absinthe.Phoenix.Endpoint

  @doc """
  Session options, built at runtime.

  The signing salt used to be a literal here, which in a public repository is a
  published secret. Nothing security-relevant rides in the session — the API
  authenticates with a bearer token — but it is still signing material, so it
  comes from config and, in production, from the environment.
  """
  def session_options do
    [
      store: :cookie,
      key: "_cartograph_backend_key",
      signing_salt: Application.fetch_env!(:cartograph_backend, :session_signing_salt),
      same_site: "Lax"
    ]
  end

  socket "/socket", CartographBackendWeb.UserSocket,
    # Origins are configuration, not source: see CartographBackendWeb.Origins.
    # `app://cartograph` is the fixed origin of the Electron desktop client; the
    # server address it points at is independent of this check.
    websocket: [check_origin: {CartographBackendWeb.Origins, :allowed_uri?, []}],
    longpoll: false

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: {__MODULE__, :session_options, []}]],
    longpoll: [connect_info: [session: {__MODULE__, :session_options, []}]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :cartograph_backend,
    gzip: not code_reloading?,
    only: CartographBackendWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :cartograph_backend
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    # 50MB cap on multipart uploads (Files area); other parsers keep defaults.
    parsers: [:urlencoded, {:multipart, length: 52_428_800}, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Corsica,
    origins: {CartographBackendWeb.Origins, :allowed?, []},
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allow_headers: ["Content-Type", "Authorization"],
    max_age: 86_400

  plug Plug.MethodOverride
  plug Plug.Head
  plug :session
  plug CartographBackendWeb.Router

  # Initialised per request rather than at compile time, so the salt can come
  # from the environment in a release.
  defp session(conn, _opts), do: Plug.Session.call(conn, Plug.Session.init(session_options()))
end
